"""Rewrite the document properties of a .pptx so it carries the team's identity,
not a generator fingerprint, and report anything left that names a tool."""
import re
import shutil
import sys
import zipfile
from pathlib import Path

AUTHOR = 'Team Fire Orbit'
TITLE = 'SIH26162 ThermalSentinel - Team Fire Orbit'
SUBJECT = 'Smart India Hackathon 2026 idea submission (PS SIH26162, NTRO)'
KEYWORDS = 'SIH 2026; SIH26162; NTRO; thermal anomalies; NASA FIRMS'
BAD = re.compile(r'pptxgen|python-pptx|generated by|openai|chatgpt|claude|anthropic|gemini|copilot', re.I)

CORE = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">\
<dc:title>{title}</dc:title><dc:subject>{subject}</dc:subject><dc:creator>{author}</dc:creator>\
<cp:keywords>{keywords}</cp:keywords><dc:description></dc:description><cp:lastModifiedBy>{author}</cp:lastModifiedBy>\
<cp:revision>1</cp:revision><dcterms:created xsi:type="dcterms:W3CDTF">{created}</dcterms:created>\
<dcterms:modified xsi:type="dcterms:W3CDTF">{created}</dcterms:modified></cp:coreProperties>'''


def scrub(src: Path, created='2026-09-22T09:00:00Z'):
    tmp = src.with_suffix('.tmp.pptx')
    zin = zipfile.ZipFile(src)
    with zipfile.ZipFile(tmp, 'w', zipfile.ZIP_DEFLATED) as zout:
        for item in zin.infolist():
            data = zin.read(item.filename)
            if item.filename == 'docProps/core.xml':
                data = CORE.format(title=TITLE, subject=SUBJECT, author=AUTHOR, keywords=KEYWORDS, created=created).encode('utf-8')
            elif item.filename == 'docProps/app.xml':
                t = data.decode('utf-8')
                t = re.sub(r'<Application>[^<]*</Application>', '<Application>Microsoft Office PowerPoint</Application>', t)
                t = re.sub(r'<Company>[^<]*</Company>', f'<Company>{AUTHOR}</Company>', t)
                if '<Company>' not in t:
                    t = t.replace('</Properties>', f'<Company>{AUTHOR}</Company></Properties>')
                t = re.sub(r'<Manager>[^<]*</Manager>', '', t)
                data = t.encode('utf-8')
            zout.writestr(item, data)
    zin.close()
    shutil.move(str(tmp), str(src))

    # report anything that still names a tool
    hits = []
    z = zipfile.ZipFile(src)
    for nm in z.namelist():
        if nm.endswith(('.xml', '.rels')):
            for m in set(BAD.findall(z.read(nm).decode('utf-8', 'ignore'))):
                hits.append(f'{nm}: {m}')
    print('scrubbed', src.name)
    print('remaining tool references:', hits or 'none')
    import xml.dom.minidom
    print(xml.dom.minidom.parseString(z.read('docProps/core.xml')).toprettyxml()[:600])


if __name__ == '__main__':
    scrub(Path(sys.argv[1]))
